### ISSUE TITLE
Where is “core.modules.model”？

### ISSUE THREAD

**Issue by LiZhi-CASIA** [jayliu0313/Shape-Guided#1]
In the 'sdf_features.py' file under the 'core' directory, the import statement on line 6 'from core.modules.model import *' is failing. It appears that the 'core.modules.model' might be missing, as both the 'load_encoder' on line 22 and 'local_decoder' functions on line 24 are likely located within this module. Could you please advise me on how to address this issue? I appreciate your assistance in advance.

**Comment by jayliu0313** [comment]
We haven't been using the 'sdf_features.py' to work, and the complete our method is in the 'rgbsdf_features.py'. You can find the methods of SDF only, RGB only and combine together there.
