### ISSUE TITLE
The poor results

### ISSUE THREAD

**Issue by LiZhi-CASIA** [jayliu0313/Shape-Guided#3]
I didn't train the 3D expert model myself. I directly used the best checkpoint of the 3D expert model in ./checkpoint. However, I obtained relatively poor results as shown in the figure below. **I'm wondering if it might be because the checkpoint isn't very good?** **Also, if I want to train the 3D expert model to get the optimal parameters, what should I do? Could you provide more details?** Thank you for the excellent work you've done. I'm looking forward to your response~

![Shape_Guided result](https://github.com/jayliu0313/Shape-Guided/assets/97828772/0d18c0d8-4daf-4edc-9c31-f382f5969480)

**Comment by jayliu0313** [comment]
I think it is impossible, the step of the setting maybe wrong.

**Comment by jayliu0313** [comment]
I think there might be a configuration mistake. Could you capture more pictures related to the settings?
Additionally, please ensure that the data has undergone preprocessing and cut_patch.

**Comment by LiZhi-CASIA** [comment]
> I think there might be a configuration mistake. Could you capture more pictures related to the settings? Additionally, please ensure that the data has undergone preprocessing and cut_patch.

Yes, the data has already undergone preprocessing and cut_patch. All the settings remained almost unchanged and I only fixed some minor bugs. 
For example, in the '**core/features.py**': line 124 is added.
<img width="1058" alt="image" src="https://github.com/jayliu0313/Shape-Guided/assets/97828772/b52aef86-5244-4acc-9638-bb3e8bb4db42">
and line 223 in the original file is modified to line 225 in my file, and line 229 is also added:
<img width="870" alt="image" src="https://github.com/jayliu0313/Shape-Guided/assets/97828772/7ac4950b-1455-4f5a-aad8-df2f30f39261">

Apart from the changes mentioned above, the other minor modifications are refinements of different versions of functions, which should not affect the results.

Below are two additional screenshots, one for **alignment.txt** and the other for **Configuration.txt**.
<img width="503" alt="image" src="https://github.com/jayliu0313/Shape-Guided/assets/97828772/d6d14fb4-bb41-436f-a6ce-ab8924baa5df">
<img width="946" alt="image" src="https://github.com/jayliu0313/Shape-Guided/assets/97828772/e8097f51-b5a7-4a7b-a8dd-739b19c62e42">

**Comment by jayliu0313** [comment]
This is a bit strange since we have tested different patches in the past, and the scores are quite similar. Additionally, we use a pretrained encoder for RGB, and it shouldn't result in such low scores. It might be necessary to spend some time to figure out this issue, and I will discuss with our team and reply you later.
I appreciate your feedback regarding the bugs. We have made adjustments to address some minor issues.

**Comment by jayliu0313** [comment]
Hello, we have retested everything, using the same code, variables, and checkpoints as on GitHub. However, the results we display still appear to be normal. Your alignment.txt and configuration.txt seem to be normal too.
Please double-check whether all the paths are correct and the processes are being executed in the correct sequence.
If you have any new leads, please kindly inform us.
Here is our results retested on our github code.
![image](https://github.com/jayliu0313/Shape-Guided/assets/43268022/d2f7650a-a3ba-428c-9e3f-ed0e5f704d82)

**Comment by LiZhi-CASIA** [comment]
The issue has been resolved. Thank you!

**Comment by jayliu0313** [comment]
You're welcome! 
However, I would like to ask you why this issue has occurred?

**Comment by LiZhi-CASIA** [comment]
> You're welcome! However, I would like to ask you why this issue has occurred?

It sounds a bit foolish, because I only preprocessed the training dataset.

**Comment by LiZhi-CASIA** [comment]
I have one more question. Is pretraining the 3D expert model required using datasets other than Mvtec3D？

**Comment by jayliu0313** [comment]
Thanks for your feedback!
No, we just use MVTec3D-AD dataset to train our 3D expert.

**Comment by LiZhi-CASIA** [comment]
> Thanks for your feedback! No, we just use MVTec3D-AD dataset to train our 3D expert.

Thanks for your timely reply.
But when I modify the variable 'IS_PRTRAIN = True' and then rerun the 'cut_patches.py', it is unable to generate the npz file. 
![image](https://github.com/jayliu0313/Shape-Guided/assets/97828772/fc5ac6f3-c44b-41c3-bef5-7a600d6b53ca)
It seems to be because there is no 'pretrain' folder under the mvtec3D dataset. Could you provide more details?

**Comment by jayliu0313** [comment]
I'm sorry. We haven't done a good job in terms of customization in this aspect. In the future, we will rewrite the "cut_patches.py" to provide pre-trained data.
Alternatively, if you're in a hurry to need, our approach is to randomly select 25 samples of tiff files from each category of the preprocessed training data as our pretrained data, and save them in the pretrained data folder. Next, you can use this pretrained data folder as your dataset_path.
If our work finished, we will tell you.

**Comment by LiZhi-CASIA** [comment]
Thanks again！I will try to obtain the necessary npz files for training as you mentioned.
Meanwhile, I'm looking forward to your future work. I'll keep following it.

**Comment by jayliu0313** [comment]
Hi, we have already rewritten the "README" and related code. You can follow the instructions to complete the "train 3D expert model".
Additionally, I suggest that you can re-clone our code. Thank you!!
