### ISSUE TITLE
A minor bug in cut_patches.py

### ISSUE THREAD

**Issue by eriche2016** [jayliu0313/Shape-Guided#7]
Hi, excelent work. 
I note that in [cut_patches.py](https://github.com/jayliu0313/Shape-Guided/blob/main/cut_patches.py#L262), 
it normalize the point cloud by following lines:
```py
pointcloud_s_t = pointcloud_s_t / (np.array([np.max(pointcloud_s[:,0]) - np.min(pointcloud_s[:,0]), np.max(pointcloud_s[:,0]) - np.min(pointcloud_s[:,0]), np.max(pointcloud_s[:,0]) - np.min(pointcloud_s[:,0])]))
```

should it be instead:
```py
pointcloud_s_t = pointcloud_s_t / (np.array([np.max(pointcloud_s[:,0]) - np.min(pointcloud_s[:,0]), np.max(pointcloud_s[:,1]) - np.min(pointcloud_s[:,1]), np.max(pointcloud_s[:,2]) - np.min(pointcloud_s[:,2])]))
```

**Comment by jayliu0313** [comment]
Thank you for your comment. 
In the past, we implement the similar method for normalization.
But normalizing each axis (x, y, and z) individually, it leads to local shape distortion, especially in the case of the z-axis. Therefore, we normalize the xyz axes with the x-axis as the basis to prevent local shapes from being stretched, while still achieving the normalization effect.

**Comment by eriche2016** [comment]
Thanks for your prompt answer. Now I understand the reasons for doing so.
