### ISSUE TITLE
main.py error

### ISSUE THREAD

**Issue by iakRulan** [jayliu0313/Shape-Guided#9]
![image](https://github.com/jayliu0313/Shape-Guided/assets/88355032/2125c89a-c909-489f-b555-2bb43fed134d)
作者你好，我在windows上进行main.py验证时出现网络问题，使用梯子也无法解决，请问有解决方法吗？

**Comment by jayliu0313** [comment]
你好，因為我們主要是用linux訓練和測試，這個問題可能沒辦法幫你解決。 另外，你的訊息上顯示timm 在載入rgb backbone model產生問題的樣子，或許你可以嘗試改用其他方式載入RGB backbone model。

**Comment by iakRulan** [comment]
我先下载权重后可以正常使用，应该是网络原因。结果已经复现，感谢你的工作！
